### ISSUE TITLE
Add Live Stableford scores

### ISSUE THREAD

**Issue by ManuAgora** [gmalewicz/golf-app#199]
When adding a round with me and my friends, would it be possible to see Live stableford scores for each player?
![image](https://github.com/gmalewicz/golf-app/assets/86299874/e288c260-996a-48f7-800f-846617e4ea9f)

**Comment by gmalewicz** [comment]
Added to backlog. I am thinking about switch between strokes/stb

**Comment by gmalewicz** [comment]
implemented - it is possible to switch between stroke play brutto and stableford netto 

![image](https://github.com/gmalewicz/golf-app/assets/57892452/def635cc-5ebd-4616-b592-75b847be3eba)
